### ISSUE TITLE
Crash of sharedb

### ISSUE THREAD

**Issue by LMessi2000** [Outlook-Suzhou/projmural-frontend#212]
WebSocket error events are not handled, so we should handle them to avoid crashing the process unnecessarily in nodejs.

**Comment by zero469** [comment]
![image](https://user-images.githubusercontent.com/36913755/178211134-e4bad7fe-b45b-458f-a7ca-4cfdb31d72ba.png)

**Comment by Yuan98Yu** [comment]
This issue was solved during the development of feature duplicate.
