### ISSUE TITLE
Port 5000 collision in local dev environment

### ISSUE THREAD

**Issue by haojianzong** [Outlook-Suzhou/projmural-frontend#239]
I am experiencing port collision and have to change to another port to run the docker when following the local deployment wiki.

<img width="457" alt="image" src="https://user-images.githubusercontent.com/4256824/178424711-f2a8d170-2891-4eb0-8588-b29193a3894a.png">

Possible solution?:
https://stackoverflow.com/questions/48281970/how-do-i-avoid-port-collision-when-using-docker

**Comment by Yuan98Yu** [comment]
This problem is caused that running a process occupying port 5000 before running our project.
The solution is whether kill the previous process or change port 5000 to another free port in the config file.
